version: "3.9"

services:
  postgres:
    image: postgres:latest
    container_name: product_postgres
    restart: always
    environment:
      POSTGRES_DB: product_postgres
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      TZ: "UTC-4"
    ports:
      - 5432:5432 
    volumes:
      - postgres-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: product_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_PORT: 4040
    ports:
      - 4040:4040
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - postgres

volumes:
  pgadmin-data:
  postgres-data:
